### ISSUE TITLE
It don't work for cts

### ISSUE THREAD

**Issue by Hexer10** [shanapu/MyJB-TG_friendlyfire#1]
I've tried this plugin  and it enabled the friendlyfire for Ts but not for CTs.

Thanks, Papero

**Comment by shanapu** [comment]
yeah, you are right. I used an older (modified) version of TG.
Seems this needs a small edit of TeamGames. 

stay tuned

**Comment by Hexer10** [comment]
Ok, thanks.
Papero

**Comment by Hexer10** [comment]
I've tryed e little workaround using a little swapteamplugin but when there is only 1T the round doesn't end any help?

`


//Includes
#include <sourcemod>
#include <sdktools>
#include <sdkhooks>
#include <myjailbreak>






//Variables
bool hastoggled;
bool hastoggledffa; 


public OnPluginStart()
{
		RegConsoleCmd("sm_setffa", Command_Setffa, "FFA swapteam");
		HookEvent("round_start", Event_RoundStart);
		HookEvent("round_end", Event_RoundEnd);        
}

public Action:Command_Setffa(int client, args)
{
	hastoggledffa = true;
}
public void Event_RoundStart(Event event, const char[] name, bool dontBroadcast)
{
	if (hastoggled)
	{
		ServerCommand("sm plugins load ratio");
        ServerCommand("mp_humanteam any"); 
		hastoggled = false;
	}
	
	if (hastoggledffa)
	{

		ServerCommand("sm_swapteama @ct");
		ServerCommand("sm plugins unload ratio");
		ServerCommand("mp_humanteam T"); 
		hastoggledffa = false;
		hastoggled = true;
	}
}

public void Event_RoundEnd(Event event, const char[] name, bool dontBroadcast)
{
   if (hastoggledffa)
   {
        ServerCommand("sm_swapteama_d @ct");
   }
   
}
		
	
	
`

**Comment by shanapu** [comment]
hi, 
sry for my late response. 
I must confess, I forgot about this issue. Forget to re/enable notification for this project.

I just opened an [issue on TeamGames](https://github.com/KissLick/TeamGames/issues/39) to fix this conflict.
I'm very ashamed and really sorry about this. I still used an old modified version of TG by mistake.

If you don't wanna wait for an Update by Kisslick you have to edit a small part in TeamGames code and compile it.

Just remove this three lines in TeamGames.sp: https://github.com/KissLick/TeamGames/blob/master/addons/sourcemod/scripting/TeamGames.sp#L379-L381

> 	// CT can't hurt CT
> 	if (iAttackerTeam == CS_TEAM_CT && iVictimTeam == CS_TEAM_CT)
> 		return Plugin_Handled;

So CT can shoot each other if no other plugin or cvar handle this friendly fire (on normal jail config this should be the state.)

If you want CTs can kill each other when MyJB-TG_friendlyfire trigger, modify line 380 in TeamGames.sp from:

> 	if (iAttackerTeam == CS_TEAM_CT && iVictimTeam == CS_TEAM_CT)

to

> 	if (!GetConVarBool(g_hNoneTeamAttack) && iAttackerTeam == CS_TEAM_CT && iVictimTeam == CS_TEAM_CT)

this should be the fix.

**Comment by shanapu** [comment]
> ... but when there is only 1T the round doesn't end any help (I'm using CS:GO) ?

IIRC in csgo a round only start/run/end when booth teams got players.

**Comment by shanapu** [comment]
This Issue should be fixed with latest version https://github.com/shanapu/MyJB-TG_friendlyfire/commit/ce9bc4bf7770e1e1c363b71eb115190854f285b7
I'm going to move this plugin to MyJailbreaks repo within next update of myjb.

**Comment by shanapu** [comment]
sry forgot to say to update teamgames to 1.1.0.7

**Comment by Hexer10** [comment]
Than I need only to update teamgames and your plugin right?

**Comment by Hexer10** [comment]
Can't compile it... ( http://pastebin.com/8HRPJ3Lz )

**Comment by shanapu** [comment]
> Than I need only to update teamgames and your plugin right?
yeah TG 1.1.0.1 and new MyJB-TG_friendlyfire 1.1 and MyJB beta 8.0

> Can't compile it... ( http://pastebin.com/8HRPJ3Lz )

You just need to compile TeamGames.sp (the other *.sp are submodules included in TeamGames.sp)

**Comment by Hexer10** [comment]
The same, beacause the TeamGames.sp need to include it i've tried to remove the includes like Convars.sp etc... but no solution.

**Comment by shanapu** [comment]
just drag and drop the TeamGames.sp onto the comp.exe 

nothing more
nothing less
